export  const  REQUEST_MUSIC_DATA = 'REQUEST_MUSIC_DATA';
export  const  RECEIVE_MUSIC_DATA_SUCCESS = 'RECEIVE_MUSIC_DATA_SUCCESS';
export  const  RECEIVE_MUSIC_DATA_FAILED = 'RECEIVE_MUSIC_DATA_FAILED';

export const GET_REQUESTED_GENRE_DETAIL = "GET_REQUESTED_GENRE_DETAIL";
export const GET_REQUESTED_GENRE_SUCCESS = "GET_REQUESTED_GENRE_SUCCESS";
export const GET_REQUESTED_GENRE_FAILED = "GET_REQUESTED_GENRE_FAILED";